name = "tether-api"
main = "src/index.ts"
compatibility_date = "2025-03-31"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "CompiledWasm", globs = ["**/*.wasm"] }
]

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "TETHER_DATA", class_name = "TetherData" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TetherData"]
