name = "tether-api"
main = "src/index.ts"
compatibility_date = "2025-03-31"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "CompiledWasm", globs = ["**/*.wasm"] }
]

[observability]
enabled = true
